import { localDescription, type Locale } from "../i18n";

// These localized descriptions summarize the existing Romanian product details.
// Demo brands, people, addresses and results are sample content, not MONO/DEV credentials.
type DetailCopy = { purpose: string; features: string[]; delivery: string };
const details: Record<number, Record<"en" | "ru", DetailCopy>> = {
  34: {
    en: { purpose: "For automotive service teams that need reception, workshop work and stock in one operational workspace.", features: ["A resource calendar and work orders tracked from arrival to handover", "Customer and vehicle histories, suppliers and separate staff roles", "Inventory reservations, replenishment alerts and tenant isolation"], delivery: "The responsive application, documented API, database structure, Docker configuration and demonstration seed." },
    ru: { purpose: "Для автосервисов, которым нужен единый рабочий кабинет для приёмки, ремонта и складского учёта.", features: ["Календарь ресурсов и заказ-наряды от приёмки до выдачи автомобиля", "История клиентов и машин, поставщики и отдельные роли сотрудников", "Резервирование запчастей, уведомления о пополнении и изоляция организаций"], delivery: "Адаптивное приложение, документированный API, структура базы, конфигурация Docker и демонстрационные данные." },
  },
  33: {
    en: { purpose: "A storefront for car electronics and accessories, built around finding products and assembling a shopping cart.", features: ["Visual categories for multimedia, audio, alarms and accessories", "Instant catalog search, favorites and an interactive cart", "Promotional slides and sections for installation services and brands"], delivery: "Editable React and Vite source, local assets and a static build ready for a real catalog and checkout integration." },
    ru: { purpose: "Витрина автомобильной электроники и аксессуаров с удобным поиском товаров и сбором заказа.", features: ["Наглядные категории мультимедиа, аудио, сигнализаций и аксессуаров", "Мгновенный поиск, избранное и интерактивная корзина", "Промослайды и разделы брендов и услуг установки"], delivery: "Редактируемый код React и Vite, локальные ресурсы и статическая сборка для подключения реального каталога и оплаты." },
  },
  32: {
    en: { purpose: "A sales workspace connecting contacts, companies and deals so a team can follow the whole commercial relationship.", features: ["A configurable Kanban pipeline with drag-and-drop and relationship timelines", "Tasks, meetings, quotes, product lists, import and export", "Trigger-based automations, user-controlled AI drafts and sales reports"], delivery: "The responsive SaaS application, isolated organization roles, Supabase schema, RLS policies, seed and production documentation." },
    ru: { purpose: "Рабочее пространство отдела продаж, связывающее контакты, компании и сделки в единую историю отношений.", features: ["Настраиваемая Kanban-воронка с перетаскиванием и историей взаимодействий", "Задачи, встречи, предложения, товары, импорт и экспорт", "Автоматизации по условиям, управляемые пользователем AI-черновики и отчёты"], delivery: "Адаптивное SaaS-приложение, роли организаций, схема Supabase, политики RLS, начальные данные и документация запуска." },
  },
  31: {
    en: { purpose: "An online learning platform for organizing a course offer and taking learners from discovery to lessons and progress.", features: ["Twelve demonstration courses, learning paths, search and filters", "Course and instructor pages with a lesson player and module navigation", "Locally saved learning progress and a complete free demonstration course"], delivery: "The LMS source, demonstration educational content, production build and showcase mode; live payments and certificates require integration." },
    ru: { purpose: "Образовательная платформа, которая ведёт ученика от выбора курса к урокам и отслеживанию прогресса.", features: ["Двенадцать демонстрационных курсов, учебные маршруты, поиск и фильтры", "Страницы курсов и преподавателей, проигрыватель уроков и модули", "Локальное сохранение прогресса и полный бесплатный демонстрационный курс"], delivery: "Код LMS, демонстрационный учебный контент, сборка и режим показа; реальные платежи и сертификаты подключаются отдельно." },
  },
  30: {
    en: { purpose: "A direct-booking website for boutique accommodation, connecting room discovery with dates, guest counts and confirmation.", features: ["Two demonstration properties, room galleries, amenities and experiences", "Availability search by property, dates and number of guests", "Rates, extras and a booking structure prepared for payments and inventory management"], delivery: "The accommodation website and booking flow, data schema, seed, pricing tests and static showcase export." },
    ru: { purpose: "Сайт прямого бронирования для небольших отелей: от знакомства с номером до выбора дат и подтверждения.", features: ["Два демонстрационных объекта, галереи номеров, удобства и впечатления", "Поиск по объекту, датам и числу гостей", "Тарифы, дополнительные услуги и структура бронирования для подключения платежей и учёта номеров"], delivery: "Сайт и сценарий бронирования, схема данных, начальные записи, тесты расчёта цен и статический экспорт." },
  },
  29: {
    en: { purpose: "A restaurant platform bringing the menu, table requests and takeaway or delivery orders into a direct customer journey.", features: ["A mobile-friendly digital menu with categories and allergens", "Reservation choices for date, time, party size and dining area", "An order cart with variants, notes, totals and selectable delivery or pickup slots"], delivery: "The responsive restaurant platform, demonstration menu, interactive flows and standalone showcase build." },
    ru: { purpose: "Платформа ресторана, объединяющая меню, заявки на столик и заказы на доставку или самовывоз.", features: ["Мобильное цифровое меню с категориями и аллергенами", "Выбор даты, времени, числа гостей и зоны ресторана", "Корзина с вариантами блюд, примечаниями, итоговой суммой и интервалами получения"], delivery: "Адаптивная платформа ресторана, демонстрационное меню, интерактивные сценарии и самостоятельная сборка." },
  },
  28: {
    en: { purpose: "A clinic website designed to make specialties and consultation choices understandable before a patient sends an appointment request.", features: ["Medical specialties, service prices and demonstration doctor profiles", "A seven-step consultation flow covering doctor, location, date, time and consent", "Demo confirmation without transmitting patient information"], delivery: "The clinic website, appointment interface, demonstration content and data structure for doctors and schedules." },
    ru: { purpose: "Сайт клиники, который помогает разобраться в специальностях и выбрать консультацию до отправки заявки.", features: ["Медицинские направления, стоимость услуг и демонстрационные профили врачей", "Запись в семь шагов: врач, филиал, дата, время и согласие", "Подтверждение в демо без передачи сведений о пациенте"], delivery: "Сайт клиники, интерфейс записи, демонстрационный контент и структура данных врачей и расписаний." },
  },
  27: {
    en: { purpose: "A real-estate catalog that helps an agency present properties, explain neighborhoods and collect viewing or valuation requests.", features: ["Twenty-four demonstration listings, detailed pages and property search", "Neighborhood information, saved favorites and similar listings", "Viewing requests and a structure for agents, media and lead administration"], delivery: "The trilingual platform, seed data, database migrations, documented images and production and showcase builds." },
    ru: { purpose: "Каталог недвижимости для агентства: презентация объектов и районов, заявки на просмотр и оценку.", features: ["Двадцать четыре демонстрационных объекта, подробные карточки и поиск", "Информация о районах, избранное и похожие предложения", "Заявки на просмотр и структура управления агентами, медиа и обращениями"], delivery: "Трёхъязычная платформа, начальные данные, миграции базы, документированные изображения и сборки для запуска и показа." },
  },
  26: {
    en: { purpose: "A universal appointment system for companies that need their own service catalog, staff availability and a branded booking page.", features: ["A guided choice of service, specialist, date and time with a booking summary", "Independent company pages, staff eligibility, prices and service durations", "Brand color and logo extraction, live theme preview and an embeddable JavaScript widget"], delivery: "Editable application source, booking and availability APIs and the multi-tenant structure for database, authentication and notification integration." },
    ru: { purpose: "Универсальная система записи для компаний со своим набором услуг, специалистами и фирменной страницей бронирования.", features: ["Пошаговый выбор услуги, специалиста, даты и времени с итоговой сводкой", "Независимые страницы компаний, расписания, цены и длительность услуг", "Извлечение цветов и логотипа бренда, предпросмотр темы и встраиваемый JavaScript-виджет"], delivery: "Редактируемый код приложения, API записи и доступности, структура для подключения базы данных, авторизации и уведомлений." },
  },
  25: {
    en: { purpose: "A rental platform for physical goods that separates commercial reservations from assigning individual units or quantities.", features: ["Configurable categories, product attributes and a trilingual catalog", "Serialized and quantity inventory with dates, locations, maintenance and availability buffers", "Hourly to monthly rates, deposits and pickup, return and damage workflows"], delivery: "The full application source, tested domain engines, Prisma database structure and the foundation for checkout and multiple locations." },
    ru: { purpose: "Платформа аренды физических товаров, разделяющая оформление брони и назначение конкретных единиц или количества.", features: ["Настраиваемые категории, атрибуты товаров и трёхъязычный каталог", "Поштучный и количественный учёт с датами, локациями, обслуживанием и буферами", "Тарифы от почасовых до месячных, залоги, выдача, возврат и фиксация повреждений"], delivery: "Полный исходный код, протестированная предметная логика, структура базы Prisma и основа для оплаты и нескольких точек выдачи." },
  },
  23: {
    en: { purpose: "A multi-page architecture portfolio for presenting residential interiors through detailed project stories and a restrained visual identity.", features: ["Individual project pages with galleries, locations, areas and editorial stories", "Dedicated studio, services and journal sections", "Contact routes from projects and services with responsive navigation"], delivery: "The editable multi-page website, project structure, visual assets and source for adapting the content to a real studio." },
    ru: { purpose: "Многостраничное портфолио архитектуры для подробной презентации жилых интерьеров в сдержанной визуальной подаче.", features: ["Отдельные проекты с галереями, локациями, площадью и редакционными историями", "Разделы студии, услуг и журнала", "Переходы к контакту из проектов и услуг, адаптивная навигация"], delivery: "Редактируемый многостраничный сайт, структура проектов, визуальные ресурсы и код для наполнения данными реальной студии." },
  },
  22: {
    en: { purpose: "An expressive interior-design portfolio where prospective clients can explore color directions before sending a project brief.", features: ["Residential and hospitality project presentations with a four-stage creative process", "An interactive color lab with Acid Dream, Night Swim and Hot Clay palettes", "An enquiry form covering city, space type and creative direction"], delivery: "React and TypeScript source, responsive interactions and the portfolio and enquiry structure for rebranding." },
    ru: { purpose: "Выразительное портфолио дизайна интерьера, где клиент изучает цветовые направления перед отправкой брифа.", features: ["Жилые и коммерческие интерьеры с описанием четырёх этапов работы", "Интерактивная лаборатория палитр Acid Dream, Night Swim и Hot Clay", "Форма с выбором города, типа пространства и творческого направления"], delivery: "Код React и TypeScript, адаптивные взаимодействия, структура портфолио и заявок для нового бренда." },
  },
  21: {
    en: { purpose: "An editorial interior-design website that uses materials, calm spaces and a visible process to help visitors develop an enquiry.", features: ["A filterable portfolio of residential, apartment and commercial interiors", "A before-and-after slider and an interactive material library", "A journal and a project request form including space type and estimated budget"], delivery: "The complete responsive website source, portfolio and material interactions, ready for original studio imagery and live forms." },
    ru: { purpose: "Редакционный сайт дизайна интерьера, который через материалы, спокойные пространства и процесс помогает сформировать заявку.", features: ["Портфолио жилых, квартирных и коммерческих интерьеров с фильтрами", "Слайдер до и после и интерактивная библиотека материалов", "Журнал и форма заявки с типом помещения и ориентиром бюджета"], delivery: "Полный код адаптивного сайта, портфолио и интерактивных материалов для собственных фотографий студии и подключения форм." },
  },
  20: {
    en: { purpose: "A contemporary furniture concept store that lets customers try a room composition and discover a style while browsing products.", features: ["Twenty-four demonstration products with search, categories, favorites and detail pages", "Room Mixer with product combinations and wall colors", "A persistent moodboard with notes, print export and a style quiz"], delivery: "The trilingual source, catalog, optimized local images and interactive tools; checkout, stock and payments can be connected separately." },
    ru: { purpose: "Магазин современной мебели, где покупатель может составить комнату и найти свой стиль во время выбора товаров.", features: ["Двадцать четыре демонстрационных товара, поиск, категории, избранное и карточки", "Room Mixer для сочетания предметов и цвета стен", "Сохраняемый мудборд с заметками, печатью и тестом стиля"], delivery: "Трёхъязычный код, каталог, оптимизированные локальные изображения и инструменты; заказы, остатки и оплата подключаются отдельно." },
  },
  19: {
    en: { purpose: "A furniture storefront that connects product selection with material origin, craft stories and repair services.", features: ["A filterable catalog with finishes, specifications and quote requests", "Product passports covering origin, materials and care", "Localized editorial content and forms for repairs, maintenance and furniture take-back"], delivery: "The multi-page catalog, editorial system and localized forms, with a structure for real products and a CMS." },
    ru: { purpose: "Мебельная витрина, связывающая выбор предмета с происхождением материалов, работой мастеров и ремонтом.", features: ["Каталог с фильтрами, отделками, характеристиками и запросами цены", "Паспорта товаров с происхождением, материалами и уходом", "Локализованный журнал и формы ремонта, обслуживания и приёма старой мебели"], delivery: "Многостраничный каталог, редакционная система и формы на трёх языках со структурой для реальных товаров и CMS." },
  },
  18: {
    en: { purpose: "A modular furniture platform for exploring how a sofa or shelving composition can fit a customer's room.", features: ["A product catalog with detailed modules, image galleries and persistent favorites", "Separate visual configurators for modular sofas and shelving", "3D scenes, changing options and estimates, with routes to quote requests"], delivery: "The complete trilingual source, original imagery, demonstration catalog and both configurators for further pricing and order integration." },
    ru: { purpose: "Платформа модульной мебели, помогающая подобрать диван или систему хранения под пространство покупателя.", features: ["Каталог с модулями, галереями и сохраняемым избранным", "Отдельные визуальные конфигураторы диванов и стеллажей", "3D-сцены, изменение параметров и оценки стоимости, переход к запросу предложения"], delivery: "Полный трёхъязычный код, исходные изображения, демонстрационный каталог и оба конфигуратора для подключения цен и заказов." },
  },
  17: {
    en: { purpose: "A B2B furniture platform for architects and procurement teams who need technical information and a structured project quotation.", features: ["A table or card catalog with specifications, finishes and document references", "A persistent Project Board with variants, quantities and an estimated total", "A validated multi-step RFQ flow that carries the selected products into the request"], delivery: "The complete B2B catalog, Project Board, resource and RFQ structure, ready for CRM and professional-account integrations." },
    ru: { purpose: "B2B-платформа мебели для архитекторов и закупщиков, которым нужны технические данные и структурированная смета проекта.", features: ["Каталог в виде таблицы или карточек с характеристиками, отделками и документами", "Сохраняемый Project Board с вариантами, количеством и оценкой общей суммы", "Пошаговый запрос предложения с проверкой полей и переносом выбранных товаров"], delivery: "Полный B2B-каталог, Project Board, раздел ресурсов и структура запросов для подключения CRM и профессиональных аккаунтов." },
  },
  16: {
    en: { purpose: "An editorial furniture website where collections and interior projects provide context for premium objects and custom enquiries.", features: ["A filterable catalog with finish, dimension and construction detail pages", "Interior project galleries linked to the products used", "A craft and materials journal and validated quote and contact forms"], delivery: "The responsive trilingual code, catalog, collections, projects and journal, prepared for real products, a CMS and CRM integration." },
    ru: { purpose: "Редакционный мебельный сайт, где коллекции и интерьеры раскрывают предметы и ведут к индивидуальному запросу.", features: ["Каталог с фильтрами, отделками, размерами и деталями изготовления", "Галереи интерьеров со ссылками на использованные предметы", "Журнал о материалах и ремесле, формы контакта и запроса цены с валидацией"], delivery: "Адаптивный трёхъязычный код, каталог, коллекции, проекты и журнал для реальных товаров, CMS и CRM." },
  },
  15: {
    en: { purpose: "A classified marketplace for local offers, connecting a searchable public catalog with seller accounts and moderation.", features: ["Category search, filtered listings and detailed offer galleries", "Personal profiles, favorites, messages and company pages", "An administration structure for listings, users, companies, banners and moderation"], delivery: "The full editable public and administration source with Firebase authentication infrastructure and a foundation for payment integration." },
    ru: { purpose: "Площадка местных объявлений, объединяющая поиск предложений, кабинеты продавцов и модерацию.", features: ["Поиск по категориям, фильтры и подробные объявления с галереями", "Личные профили, избранное, сообщения и страницы компаний", "Панель управления объявлениями, пользователями, компаниями, баннерами и модерацией"], delivery: "Полный редактируемый код публичной части и администрирования, инфраструктура авторизации Firebase и основа для подключения оплаты." },
  },
  14: {
    en: { purpose: "A barber-shop website for explaining services, presenting work and directing visitors to appointments or professional courses.", features: ["Service presentations with prices and routes to external booking", "An editorial work gallery and configurable barber profile content", "A separate academy section, cinematic intro and responsive mobile navigation"], delivery: "The editable website, animations and centralized content for real services, barbers, booking links and courses." },
    ru: { purpose: "Сайт барбершопа с услугами, портфолио и переходами к записи или профессиональному обучению.", features: ["Презентация услуг с ценами и переходами к внешней системе записи", "Редакционная галерея работ и настраиваемое содержание профиля мастера", "Отдельный раздел академии, кинематографическое вступление и мобильная навигация"], delivery: "Редактируемый сайт, анимации и централизованное содержание для реальных услуг, мастеров, записи и курсов." },
  },
  12: {
    en: { purpose: "An equipment-rental catalog for companies that need to explain specifications and daily rates before receiving a rental enquiry.", features: ["Construction, energy and access-equipment categories with instant search", "Availability labels, equipment specifications and daily rental prices", "An administration area for the prices displayed in the public catalog"], delivery: "The public catalog and management source, responsive interface and a structure for real inventory and enquiries." },
    ru: { purpose: "Каталог аренды техники для компаний, которым нужно показать характеристики и суточные тарифы перед получением заявки.", features: ["Категории строительной, энергетической и высотной техники с быстрым поиском", "Отметки доступности, характеристики и суточная стоимость аренды", "Раздел управления ценами, опубликованными в каталоге"], delivery: "Код каталога и управления, адаптивный интерфейс и структура для реального парка техники и заявок." },
  },
  11: {
    en: { purpose: "A nail-studio website that separates appointments from academy enquiries so clients and learners find the right offer.", features: ["Service descriptions including duration and starting prices", "Course offers for beginner, intermediate and advanced learners", "An interactive enquiry form for services, courses and custom requests"], delivery: "The editable responsive design and centralized service and course content, ready for a booking platform or CRM." },
    ru: { purpose: "Сайт ногтевой студии, разделяющий запись на услуги и запросы об обучении для клиентов и будущих мастеров.", features: ["Описание услуг с продолжительностью и стартовой ценой", "Курсы для начинающего, среднего и продвинутого уровней", "Интерактивная форма для услуг, курсов и индивидуальных запросов"], delivery: "Редактируемый адаптивный дизайн и централизованное содержание услуг и курсов для подключения записи или CRM." },
  },
  10: {
    en: { purpose: "A workshop dashboard replacing fragmented spreadsheets with a view of vehicles, jobs, customers and the team's workload.", features: ["Work orders, appointments, estimates and customer or vehicle records", "Parts inventory with minimum-stock alerts and staff task information", "Revenue reports, local data persistence and CSV exports for operational modules"], delivery: "The complete dashboard and modules with demonstration data, ready for a real database, authentication and notification integration." },
    ru: { purpose: "Кабинет автосервиса, который собирает машины, работы, клиентов и загрузку команды вместо разрозненных таблиц.", features: ["Заказ-наряды, записи, сметы и карточки клиентов и автомобилей", "Склад запчастей с порогами остатков и задания сотрудников", "Отчёты о выручке, локальное сохранение и экспорт CSV по модулям"], delivery: "Полный кабинет и модули с демонстрационными данными для подключения базы, авторизации и уведомлений." },
  },
  9: {
    en: { purpose: "A shared calendar for couples, families and small groups who want to settle on a plan and keep participants informed.", features: ["Calendar and list views, custom activities and configurable reminders", "Partner requests, reusable groups and accepted or declined plan changes", "Integration structure for Google sign-in, Firebase and Telegram notifications"], delivery: "The editable event, partner and group application source and integration configuration; external accounts and credentials are supplied separately." },
    ru: { purpose: "Общий календарь для пар, семей и небольших групп, которым нужно согласовать планы и уведомить участников.", features: ["Календарь и список, собственные занятия и настраиваемые напоминания", "Запросы партнёрства, повторно используемые группы и согласование изменений", "Структура интеграций Google-входа, Firebase и уведомлений Telegram"], delivery: "Редактируемый код событий, партнёров и групп с конфигурацией интеграций; внешние аккаунты и ключи предоставляются отдельно." },
  },
  8: {
    en: { purpose: "A residential-community platform that organizes meter readings, supporting photos, consumption charges and communication with residents.", features: ["A resident portal for water and electricity readings and payment history", "Administrator review of readings, tariffs, payments and community contributions", "Multiple community areas with separate roles and trilingual resident content"], delivery: "The resident and administration source and utility data structure, ready for configuration with a community's real tariffs and accounts." },
    ru: { purpose: "Платформа жилого сообщества для показаний счётчиков, подтверждающих фотографий, начислений и общения с жильцами.", features: ["Кабинет жильца с показаниями воды и электричества и историей оплат", "Проверка показаний, тарифы, оплаты и взносы в панели администратора", "Несколько жилых зон, отдельные роли и содержание на трёх языках"], delivery: "Код кабинетов жильца и администратора, структура коммунальных данных для настройки реальных тарифов и аккаунтов сообщества." },
  },
  7: {
    en: { purpose: "A beauty-salon website that presents treatments and the salon's visual identity while giving visitors a clear route to an appointment enquiry.", features: ["Interactive hair, nail, skincare and brow service sections", "A salon-story page and an extensive visual gallery", "Trilingual content, responsive navigation and an appointment enquiry form"], delivery: "The complete editable source, presented pages and responsive design for rebranding with a real salon's services and imagery." },
    ru: { purpose: "Сайт салона красоты, который знакомит с процедурами и визуальным стилем и ведёт посетителя к заявке на запись.", features: ["Интерактивные разделы волос, ногтей, ухода за кожей и бровей", "Страница истории салона и обширная визуальная галерея", "Три языка, адаптивная навигация и форма заявки на запись"], delivery: "Полный редактируемый код, представленные страницы и адаптивный дизайн для реальных услуг и фотографий салона." },
  },
};

export function legacyProjectDetails(locale: Exclude<Locale, "ro">, project: { id: number; title: string; desc: string; stack: string[] }) {
  const content = details[project.id]?.[locale];
  if (!content) return undefined;
  return {
    summary: `${localDescription(project.id, project.desc, locale)} ${content.purpose}`,
    sections: [
      { title: locale === "en" ? "Main functions" : "Основные функции", items: content.features },
      { title: locale === "en" ? "What the buyer receives" : "Что получает покупатель", items: [content.delivery] },
    ],
  };
}
