// Generated by scripts/generate-project-card-images.mjs. Originals are preserved.
export const projectCardImages: Record<string, { fallback: string; srcSet: string; width: number; height: number }> = {
  "serviceflow-pro": {
    "fallback": "/project-card-previews/serviceflow-pro-800.webp",
    "srcSet": "/project-card-previews/serviceflow-pro-480.webp 480w, /project-card-previews/serviceflow-pro-800.webp 800w",
    "width": 800,
    "height": 600
  },
  "vatra-market": {
    "fallback": "/project-card-previews/vatra-market-800.webp",
    "srcSet": "/project-card-previews/vatra-market-480.webp 480w, /project-card-previews/vatra-market-800.webp 800w",
    "width": 800,
    "height": 600
  },
  "codru-escapes": {
    "fallback": "/project-card-previews/codru-escapes-800.webp",
    "srcSet": "/project-card-previews/codru-escapes-480.webp 480w, /project-card-previews/codru-escapes-800.webp 800w",
    "width": 800,
    "height": 600
  },
  "clientaxis-crm": {
    "fallback": "/project-card-previews/clientaxis-crm-800.webp",
    "srcSet": "/project-card-previews/clientaxis-crm-480.webp 480w, /project-card-previews/clientaxis-crm-800.webp 800w",
    "width": 800,
    "height": 600
  },
  "iclinica": {
    "fallback": "/project-card-previews/iclinica-800.webp",
    "srcSet": "/project-card-previews/iclinica-480.webp 480w, /project-card-previews/iclinica-800.webp 800w",
    "width": 800,
    "height": 600
  },
  "aquaverde": {
    "fallback": "/project-card-previews/aquaverde-800.webp",
    "srcSet": "/project-card-previews/aquaverde-480.webp 480w, /project-card-previews/aquaverde-800.webp 800w",
    "width": 800,
    "height": 497
  },
  "terraforma": {
    "fallback": "/project-card-previews/terraforma-800.webp",
    "srcSet": "/project-card-previews/terraforma-480.webp 480w, /project-card-previews/terraforma-800.webp 800w",
    "width": 800,
    "height": 450
  },
  "gazonpro": {
    "fallback": "/project-card-previews/gazonpro-800.webp",
    "srcSet": "/project-card-previews/gazonpro-480.webp 480w, /project-card-previews/gazonpro-800.webp 800w",
    "width": 800,
    "height": 450
  },
  "ecohabitat": {
    "fallback": "/project-card-previews/ecohabitat-800.webp",
    "srcSet": "/project-card-previews/ecohabitat-480.webp 480w, /project-card-previews/ecohabitat-800.webp 800w",
    "width": 800,
    "height": 534
  },
  "yardcraft": {
    "fallback": "/project-card-previews/yardcraft-800.webp",
    "srcSet": "/project-card-previews/yardcraft-480.webp 480w, /project-card-previews/yardcraft-800.webp 800w",
    "width": 800,
    "height": 600
  },
  "01-eventora": {
    "fallback": "/project-card-previews/01-eventora-800.webp",
    "srcSet": "/project-card-previews/01-eventora-480.webp 480w, /project-card-previews/01-eventora-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "02-scena-city": {
    "fallback": "/project-card-previews/02-scena-city-800.webp",
    "srcSet": "/project-card-previews/02-scena-city-480.webp 480w, /project-card-previews/02-scena-city-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "03-pulse-tickets": {
    "fallback": "/project-card-previews/03-pulse-tickets-800.webp",
    "srcSet": "/project-card-previews/03-pulse-tickets-480.webp 480w, /project-card-previews/03-pulse-tickets-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "04-clinica-nova": {
    "fallback": "/project-card-previews/04-clinica-nova-800.webp",
    "srcSet": "/project-card-previews/04-clinica-nova-480.webp 480w, /project-card-previews/04-clinica-nova-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "05-laboris": {
    "fallback": "/project-card-previews/05-laboris-800.webp",
    "srcSet": "/project-card-previews/05-laboris-480.webp 480w, /project-card-previews/05-laboris-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "06-doctor-aproape": {
    "fallback": "/project-card-previews/06-doctor-aproape-800.webp",
    "srcSet": "/project-card-previews/06-doctor-aproape-480.webp 480w, /project-card-previews/06-doctor-aproape-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "07-med-slot": {
    "fallback": "/project-card-previews/07-med-slot-800.webp",
    "srcSet": "/project-card-previews/07-med-slot-480.webp 480w, /project-card-previews/07-med-slot-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "08-lead-pilot": {
    "fallback": "/project-card-previews/08-lead-pilot-800.webp",
    "srcSet": "/project-card-previews/08-lead-pilot-480.webp 480w, /project-card-previews/08-lead-pilot-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "09-growth-desk": {
    "fallback": "/project-card-previews/09-growth-desk-800.webp",
    "srcSet": "/project-card-previews/09-growth-desk-480.webp 480w, /project-card-previews/09-growth-desk-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "10-closeflow": {
    "fallback": "/project-card-previews/10-closeflow-800.webp",
    "srcSet": "/project-card-previews/10-closeflow-480.webp 480w, /project-card-previews/10-closeflow-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "11-partmatch": {
    "fallback": "/project-card-previews/11-partmatch-800.webp",
    "srcSet": "/project-card-previews/11-partmatch-480.webp 480w, /project-card-previews/11-partmatch-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "12-garage-box": {
    "fallback": "/project-card-previews/12-garage-box-800.webp",
    "srcSet": "/project-card-previews/12-garage-box-480.webp 480w, /project-card-previews/12-garage-box-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "13-motor-supply": {
    "fallback": "/project-card-previews/13-motor-supply-800.webp",
    "srcSet": "/project-card-previews/13-motor-supply-480.webp 480w, /project-card-previews/13-motor-supply-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "14-auto-grid": {
    "fallback": "/project-card-previews/14-auto-grid-800.webp",
    "srcSet": "/project-card-previews/14-auto-grid-480.webp 480w, /project-card-previews/14-auto-grid-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "15-park-suites-demo": {
    "fallback": "/project-card-previews/15-park-suites-demo-800.webp",
    "srcSet": "/project-card-previews/15-park-suites-demo-480.webp 480w, /project-card-previews/15-park-suites-demo-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "16-urban-haven": {
    "fallback": "/project-card-previews/16-urban-haven-800.webp",
    "srcSet": "/project-card-previews/16-urban-haven-480.webp 480w, /project-card-previews/16-urban-haven-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "17-nest-collection": {
    "fallback": "/project-card-previews/17-nest-collection-800.webp",
    "srcSet": "/project-card-previews/17-nest-collection-480.webp 480w, /project-card-previews/17-nest-collection-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "18-moldova-escape": {
    "fallback": "/project-card-previews/18-moldova-escape-800.webp",
    "srcSet": "/project-card-previews/18-moldova-escape-480.webp 480w, /project-card-previews/18-moldova-escape-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "19-bazar-local": {
    "fallback": "/project-card-previews/19-bazar-local-800.webp",
    "srcSet": "/project-card-previews/19-bazar-local-480.webp 480w, /project-card-previews/19-bazar-local-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "20-pret-bun": {
    "fallback": "/project-card-previews/20-pret-bun-800.webp",
    "srcSet": "/project-card-previews/20-pret-bun-480.webp 480w, /project-card-previews/20-pret-bun-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "21-local-craft": {
    "fallback": "/project-card-previews/21-local-craft-800.webp",
    "srcSet": "/project-card-previews/21-local-craft-480.webp 480w, /project-card-previews/21-local-craft-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "22-skillup": {
    "fallback": "/project-card-previews/22-skillup-800.webp",
    "srcSet": "/project-card-previews/22-skillup-480.webp 480w, /project-card-previews/22-skillup-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "23-civic-learn": {
    "fallback": "/project-card-previews/23-civic-learn-800.webp",
    "srcSet": "/project-card-previews/23-civic-learn-480.webp 480w, /project-card-previews/23-civic-learn-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "24-mentor-cloud": {
    "fallback": "/project-card-previews/24-mentor-cloud-800.webp",
    "srcSet": "/project-card-previews/24-mentor-cloud-480.webp 480w, /project-card-previews/24-mentor-cloud-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "25-casa-check": {
    "fallback": "/project-card-previews/25-casa-check-800.webp",
    "srcSet": "/project-card-previews/25-casa-check-480.webp 480w, /project-card-previews/25-casa-check-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "26-direct-home": {
    "fallback": "/project-card-previews/26-direct-home-800.webp",
    "srcSet": "/project-card-previews/26-direct-home-480.webp 480w, /project-card-previews/26-direct-home-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "27-area-insight": {
    "fallback": "/project-card-previews/27-area-insight-800.webp",
    "srcSet": "/project-card-previews/27-area-insight-480.webp 480w, /project-card-previews/27-area-insight-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "28-table-flow": {
    "fallback": "/project-card-previews/28-table-flow-800.webp",
    "srcSet": "/project-card-previews/28-table-flow-480.webp 480w, /project-card-previews/28-table-flow-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "29-food-route": {
    "fallback": "/project-card-previews/29-food-route-800.webp",
    "srcSet": "/project-card-previews/29-food-route-480.webp 480w, /project-card-previews/29-food-route-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "30-menu-studio": {
    "fallback": "/project-card-previews/30-menu-studio-800.webp",
    "srcSet": "/project-card-previews/30-menu-studio-480.webp 480w, /project-card-previews/30-menu-studio-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "31-my-utility": {
    "fallback": "/project-card-previews/31-my-utility-800.webp",
    "srcSet": "/project-card-previews/31-my-utility-480.webp 480w, /project-card-previews/31-my-utility-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "32-block-admin": {
    "fallback": "/project-card-previews/32-block-admin-800.webp",
    "srcSet": "/project-card-previews/32-block-admin-480.webp 480w, /project-card-previews/32-block-admin-800.webp 800w",
    "width": 800,
    "height": 667
  },
  "autoflow-partner": {
    "fallback": "/project-card-previews/autoflow-partner-800.webp",
    "srcSet": "/project-card-previews/autoflow-partner-480.webp 480w, /project-card-previews/autoflow-partner-800.webp 800w",
    "width": 800,
    "height": 380
  },
  "drivolt": {
    "fallback": "/project-card-previews/drivolt-800.webp",
    "srcSet": "/project-card-previews/drivolt-480.webp 480w, /project-card-previews/drivolt-800.webp 800w",
    "width": 800,
    "height": 506
  },
  "flow-crm": {
    "fallback": "/project-card-previews/flow-crm-800.webp",
    "srcSet": "/project-card-previews/flow-crm-480.webp 480w, /project-card-previews/flow-crm-800.webp 800w",
    "width": 800,
    "height": 507
  },
  "academia": {
    "fallback": "/project-card-previews/academia-800.webp",
    "srcSet": "/project-card-previews/academia-480.webp 480w, /project-card-previews/academia-800.webp 800w",
    "width": 800,
    "height": 507
  },
  "staynest": {
    "fallback": "/project-card-previews/staynest-800.webp",
    "srcSet": "/project-card-previews/staynest-480.webp 480w, /project-card-previews/staynest-800.webp 800w",
    "width": 800,
    "height": 507
  },
  "tableo": {
    "fallback": "/project-card-previews/tableo-800.webp",
    "srcSet": "/project-card-previews/tableo-480.webp 480w, /project-card-previews/tableo-800.webp 800w",
    "width": 800,
    "height": 507
  },
  "medora-clinic": {
    "fallback": "/project-card-previews/medora-clinic-800.webp",
    "srcSet": "/project-card-previews/medora-clinic-480.webp 480w, /project-card-previews/medora-clinic-800.webp 800w",
    "width": 800,
    "height": 507
  },
  "imobilia-one": {
    "fallback": "/project-card-previews/imobilia-one-800.webp",
    "srcSet": "/project-card-previews/imobilia-one-480.webp 480w, /project-card-previews/imobilia-one-800.webp 800w",
    "width": 800,
    "height": 507
  }
};
