import { notFound } from "next/navigation";
import { SeoShell } from "../../../components/seo-shell";
import { JsonLd } from "../../../components/json-ld";
import { isLocale, localePath, locales, type Locale } from "../../../lib/site-config";
import { getProject, installmentPlans, monthlyRentalPrice, projectHref, publicProjects, categoryServiceSlugs } from "../../../lib/project-catalog";
import { projectMetadata, projectStructuredData, projectTitle } from "../../../lib/project-seo";
import "../../../project-pages.css";

type Params = { locale: string; slug: string };
export const dynamicParams = false;
export function generateStaticParams() {
  return locales.flatMap(locale => publicProjects.map(project => ({ locale, slug: project.slug })));
}

function resolveProject(params: Params) {
  if (!isLocale(params.locale)) notFound();
  const project = getProject(params.locale, params.slug);
  if (!project) notFound();
  return { locale: params.locale, project };
}

export async function generateMetadata({ params }: { params: Promise<Params> }) {
  const { locale, project } = resolveProject(await params);
  return projectMetadata(locale, project);
}

const labels = {
  ro: { use: "Pentru cine este potrivit", demo: "Deschide demo-ul", screenshot: "Captură din demonstrația proiectului", artwork: "Imagine din demonstrația proiectului", note: "Acesta este un proiect demonstrativ disponibil pentru personalizare. Numele, persoanele, recenziile, adresele și rezultatele din demo sunt conținut de exemplu, nu clienți sau realizări MONO/DEV. Conturile, datele reale și integrările externe se configurează pentru lansarea ta.", technologies: "Tehnologii", price: "Prețul proiectului", available: "Disponibil pentru personalizare", purchase: "Solicită proiectul", installments: "Plata în rate", months: "Luni", monthly: "Lunar", total: "Total", rent: "Chirie lunară", rentalDetails: "Chiria de bază nu include găzduire și mentenanță. Pachetul suplimentar existent este €40/lună: găzduire €10, mentenanță €20, securitate și backup €10.", discussRental: "Discută chiria", terms: "Conținutul livrării, integrarea serviciilor și condițiile contractuale se confirmă înainte de comandă.", related: "Proiecte similare", services: "Personalizare și lansare", customize: "Personalizarea proiectului", ready: "Site-uri gata de lansare", contact: "Discută cerințele tale", faq: "Întrebări despre achiziție", problem: "De la demonstrație la proiectul tău", guidance: "Verifică fluxurile de mai jos în demo, apoi notează ce vrei să păstrezi și ce trebuie adaptat afacerii tale. Discuția pornește de la aceste funcții concrete, de la conținutul propriu și de la serviciile care trebuie conectate." },
  ru: { use: "Кому подходит проект", demo: "Открыть демо", screenshot: "Снимок демонстрационной версии", artwork: "Изображение из демонстрационной версии", note: "Это демонстрационный проект, доступный для адаптации. Имена, люди, отзывы, адреса и результаты в демо — примеры содержания, а не клиенты или достижения MONO/DEV. Аккаунты, реальные данные и внешние интеграции настраиваются для вашего запуска.", technologies: "Технологии", price: "Стоимость проекта", available: "Доступен для адаптации", purchase: "Запросить проект", installments: "Оплата в рассрочку", months: "Месяцы", monthly: "В месяц", total: "Итого", rent: "Ежемесячная аренда", rentalDetails: "Базовая аренда не включает хостинг и обслуживание. Дополнительный пакет стоит €40 в месяц: хостинг €10, обслуживание €20, безопасность и резервные копии €10.", discussRental: "Обсудить аренду", terms: "Состав поставки, подключение сервисов и условия договора согласуются до заказа.", related: "Похожие проекты", services: "Адаптация и запуск", customize: "Адаптация проекта", ready: "Готовые сайты", contact: "Обсудить ваши требования", faq: "Вопросы о покупке", problem: "От демонстрации к вашему проекту", guidance: "Проверьте описанные ниже сценарии в демо и отметьте, что подходит вашей компании и что нужно изменить. Обсуждение строится вокруг конкретных функций, собственного содержания и сервисов, которые предстоит подключить." },
  en: { use: "Who this project is for", demo: "Open the demo", screenshot: "Screenshot of the project demonstration", artwork: "Image from the project demonstration", note: "This is a demonstration project available for customization. Names, people, reviews, addresses and results in the demo are sample content, not MONO/DEV clients or achievements. Accounts, live data and external integrations are configured for your launch.", technologies: "Technologies", price: "Project price", available: "Available for customization", purchase: "Request this project", installments: "Installment options", months: "Months", monthly: "Monthly", total: "Total", rent: "Monthly rental", rentalDetails: "The base rental excludes hosting and maintenance. The existing optional service package is €40/month: hosting €10, maintenance €20, security and backups €10.", discussRental: "Discuss rental", terms: "The delivery scope, service integrations and contractual terms are confirmed before an order.", related: "Related projects", services: "Customization and launch", customize: "Project customization", ready: "Launch-ready websites", contact: "Discuss your requirements", faq: "Purchase questions", problem: "From demonstration to your project", guidance: "Try the flows below in the demo and note which parts suit your business and which need to change. The discussion starts with these specific functions, your own content and the services that need to be connected." },
} as const;

const audience: Record<string, Record<Locale, string>> = {
  "Gardens & Landscaping": { ro: "Pentru firme de amenajări și întreținere a spațiilor verzi care vor să își prezinte oferta și să ajute vizitatorii să contureze o cerere.", ru: "Для компаний по благоустройству и уходу за зелёными зонами, которым нужна презентация услуг и помощь посетителю в подготовке заявки.", en: "For landscaping and garden-care businesses that want to present their services and help visitors define an enquiry." },
  "Clinics & Medical": { ro: "Pentru clinici și cabinete care au nevoie de servicii medicale ușor de găsit și de un parcurs clar până la solicitarea unei programări.", ru: "Для клиник и кабинетов, которым нужны понятный каталог медицинских услуг и последовательный путь к заявке на запись.", en: "For clinics and practices that need discoverable services and a clear path to an appointment request." },
  "Restaurants & Food": { ro: "Pentru restaurante și afaceri de alimentație care vor să prezinte meniul, disponibilitatea sau modalitatea de comandă într-un singur loc.", ru: "Для ресторанов и предприятий питания, которым нужно собрать меню, условия посещения или заказа в одном месте.", en: "For restaurants and food businesses that want a single place for their menu, visit planning or ordering experience." },
  "Real Estate": { ro: "Pentru agenții și echipe imobiliare care trebuie să organizeze oferta și să transforme interesul pentru un obiect într-o cerere concretă.", ru: "Для агентств и команд недвижимости, которым нужно систематизировать предложения и превращать интерес к объекту в конкретную заявку.", en: "For real-estate agencies and teams that need to organize listings and turn interest in a property into a specific enquiry." },
  "E-commerce & Auto": { ro: "Pentru comercianți de piese, accesorii și produse auto care au nevoie de o ofertă ușor de căutat și comparat.", ru: "Для продавцов запчастей, аксессуаров и автотоваров, которым нужен удобный поиск и сравнение предложений.", en: "For automotive parts and accessory retailers that need an offer customers can search and compare." },
  "Hotels & Travel": { ro: "Pentru afaceri de cazare și turism care vor să explice opțiunile și să ajute vizitatorul să își planifice șederea sau călătoria.", ru: "Для гостиничных и туристических проектов, которые помогают посетителю выбрать вариант проживания или спланировать поездку.", en: "For accommodation and travel businesses that want to explain their options and help visitors plan a stay or trip." },
  "CRM & Sales": { ro: "Pentru echipe comerciale care au nevoie de vizibilitate asupra contactelor, oportunităților și acțiunilor următoare.", ru: "Для отделов продаж, которым нужен обзор контактов, сделок и следующих действий.", en: "For sales teams that need a clear view of contacts, opportunities and the next action." },
  "Online Education": { ro: "Pentru furnizori de cursuri și programe educaționale care trebuie să organizeze oferta și experiența de învățare.", ru: "Для поставщиков курсов и учебных программ, которым нужно организовать каталог и процесс обучения.", en: "For course and learning-program providers that need to organize their offer and learner experience." },
  "Interior Design": { ro: "Pentru studiouri de arhitectură și design interior care își prezintă proiectele, materialele și procesul înainte de o discuție cu clientul.", ru: "Для архитектурных и интерьерных студий, которые показывают проекты, материалы и процесс до обсуждения заявки.", en: "For architecture and interior-design studios presenting projects, materials and their process before a client enquiry." },
  "Mobilă": { ro: "Pentru branduri și furnizori de mobilier care vor să prezinte produse și specificații într-un context vizual potrivit cumpărătorului.", ru: "Для мебельных брендов и поставщиков, которым нужна наглядная презентация товаров и характеристик для своей аудитории.", en: "For furniture brands and suppliers that need to present products and specifications in a visual context suited to their buyers." },
  "Marketplace": { ro: "Pentru operatori de cataloage, anunțuri și piețe online care trebuie să conecteze oferta vânzătorilor cu o căutare relevantă.", ru: "Для операторов каталогов, объявлений и маркетплейсов, связывающих предложения продавцов с поиском покупателя.", en: "For catalog, classified and marketplace operators connecting seller offers with relevant buyer searches." },
  "Equipment Rental": { ro: "Pentru firme care închiriază bunuri fizice și au nevoie de catalog, tarife și o evidență clară a disponibilității.", ru: "Для компаний по аренде физических товаров, которым нужны каталог, тарифы и понятный учёт доступности.", en: "For physical-goods rental businesses that need a catalog, rates and a clear view of availability." },
  "Beauty & Academy": { ro: "Pentru saloane, specialiști și academii de beauty care trebuie să distingă serviciile pentru clienți de oferta de formare.", ru: "Для салонов, специалистов и бьюти-академий, которым нужно разграничить услуги клиентам и обучение.", en: "For salons, specialists and beauty academies that need to distinguish customer services from professional training." },
  "Service Management": { ro: "Pentru ateliere și firme de servicii care vor să centralizeze programările, lucrările și relația cu clienții.", ru: "Для мастерских и сервисных компаний, которые хотят объединить записи, работы и отношения с клиентами.", en: "For workshops and service companies that want to centralize appointments, jobs and customer relationships." },
  "Calendar & Events": { ro: "Pentru proiecte de evenimente și planificare care trebuie să prezinte opțiunile și să coordoneze participarea.", ru: "Для событийных и планировочных проектов, которым нужно представить варианты и согласовать участие.", en: "For event and planning projects that need to present options and coordinate participation." },
  "Utility Management": { ro: "Pentru administratori și comunități rezidențiale care vor să organizeze consumul, contribuțiile și comunicarea cu locatarii.", ru: "Для управляющих и жилых сообществ, которым нужно организовать потребление, взносы и общение с жильцами.", en: "For property managers and residential communities that need to organize usage, contributions and resident communication." },
};

export default async function ProjectPage({ params }: { params: Promise<Params> }) {
  const { locale, project } = resolveProject(await params);
  const c = labels[locale];
  const path = `projects/${project.slug}`;
  const contact = (option: string) => `${localePath(locale, "contact")}?${new URLSearchParams({ project: project.title, option })}`;
  const similar = publicProjects.filter(candidate => candidate.id !== project.id && candidate.type === project.type).slice(0, 3);
  const related = (similar.length ? similar : publicProjects.filter(candidate => candidate.id !== project.id).slice(0, 3)).map(candidate => getProject(locale, candidate.slug)!);
  const schema = projectStructuredData(locale, project);
  return <SeoShell locale={locale} path={path} title={projectTitle(project, locale)} description={project.detail.summary}>
    <div className="project-product">
      <article className="project-content">
        <p className="project-demo-note">{c.note}</p>
        {project.image && <figure className="project-shot"><img src={project.image.src} alt={project.image.alt} width={project.image.width} height={project.image.height} decoding="async" loading="lazy" /><figcaption>{c.screenshot}: {project.title}.</figcaption></figure>}
        <section><h2>{c.use}</h2><p>{audience[project.type]?.[locale]}</p></section>
        {project.detail.sections.map((section, index) => <section key={`${index}-${section.title}`}><h2>{section.title}</h2><ul>{section.items.map((item, itemIndex) => <li key={`${itemIndex}-${item}`}>{item}</li>)}</ul></section>)}
        <section><h2>{c.technologies}</h2><ul>{project.stack.map(technology => <li key={technology}>{technology === "Stocare locală" ? { ro: technology, ru: "Локальное хранение", en: "Local storage" }[locale] : technology === "CSS responsive" ? { ro: "CSS responsive", ru: "Адаптивный CSS", en: "Responsive CSS" }[locale] : technology}</li>)}</ul></section>
        <section><h2>{c.problem}</h2><p>{c.guidance}</p><a className="project-action" href={project.demo} data-analytics-event="demo_open" data-project={project.slug}>{c.demo} — {project.title}</a></section>
        <section><h2>{c.services}</h2><div className="project-service-links"><a href={localePath(locale, `services/${categoryServiceSlugs[project.type] ?? "business-websites"}`)}>{project.category}</a><a href={localePath(locale, "services/website-customization")}>{c.customize}</a><a href={localePath(locale, "services/launch-ready-websites")}>{c.ready}</a><a href={localePath(locale, "intrebari")}>{c.faq}</a><a href={localePath(locale, "contact")}>{c.contact}</a></div></section>
      </article>
      <aside className="project-purchase" aria-label={c.price}>
        <h2>{c.price}</h2><strong>€{project.price}</strong><small>{c.available} · EUR</small>
        <a href={contact("purchase")} data-analytics-event="project_request" data-project={project.slug}>{c.purchase}</a>
        <h3>{c.installments}</h3><table className="project-payment-table"><thead><tr><th scope="col">{c.months}</th><th scope="col">{c.monthly}</th><th scope="col">{c.total}</th></tr></thead><tbody>{installmentPlans.map(plan => { const total = Math.ceil(project.price * (1 + plan.surcharge)); return <tr key={plan.months}><th scope="row"><a className="project-secondary" href={contact(`installments-${plan.months}-months`)} data-analytics-event="payment_option" data-project={project.slug} data-option={`installments-${plan.months}-months`}>{plan.months}</a></th><td>€{(total / plan.months).toFixed(2)}</td><td>€{total}</td></tr>; })}</tbody></table>
        <h3>{c.rent}</h3><p>€{monthlyRentalPrice(project.price).toFixed(2)} / {locale === "ro" ? "lun\u0103" : locale === "ru" ? "\u043c\u0435\u0441\u044f\u0446" : "month"}</p><small>{c.rentalDetails}</small><a className="project-secondary" href={contact("site-rental-without-services")} data-analytics-event="payment_option" data-project={project.slug} data-option="site-rental-without-services">{c.discussRental}</a><small>{c.terms}</small>
      </aside>
    </div>
    <section className="project-content"><h2>{c.related}</h2><div className="project-related">{related.map(candidate => <article key={candidate.id}><h3><a href={projectHref(locale, candidate.id)} data-analytics-event="project_open" data-project={candidate.slug}>{candidate.title}</a></h3><p>{candidate.description}</p><p>€{candidate.price}</p></article>)}</div></section>
    {schema && <JsonLd data={schema} />}
  </SeoShell>;
}
