import { readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { loadSiteModule } from "./load-site-data.mjs";

export async function demoDirectories(root = process.cwd()) {
  const publicRoot = path.join(root, "public");
  async function hasHtml(directory) {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      if (entry.isFile() && entry.name.endsWith(".html")) return true;
      if (entry.isDirectory() && !["node_modules", "assets", "images", "_next"].includes(entry.name) && await hasHtml(path.join(directory, entry.name))) return true;
    }
    return false;
  }
  const directories = [];
  for (const entry of await readdir(publicRoot, { withFileTypes: true })) {
    if (entry.isDirectory() && !["ro", "ru", "en"].includes(entry.name) && await hasHtml(path.join(publicRoot, entry.name))) directories.push(entry.name);
  }
  return directories.sort();
}

export async function demoHtmlPaths(root = process.cwd(), directories) {
  const publicRoot = path.join(root, "public");
  const paths = new Set();
  async function visit(directory) {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const filename = path.join(directory, entry.name);
      if (entry.isDirectory() && !["node_modules", "assets", "images", "_next"].includes(entry.name)) await visit(filename);
      else if (entry.isFile() && entry.name.endsWith(".html")) {
        const pathname = `/${path.relative(publicRoot, filename).split(path.sep).map(encodeURIComponent).join("/")}`;
        paths.add(pathname);
        // Netlify serves .html files at their extensionless aliases; index.html
        // also supplies the parent directory. No rule covers image/JS/CSS files.
        paths.add(pathname.slice(0, -5));
        paths.add(`${pathname.slice(0, -5)}/`);
        if (entry.name === "index.html") {
          paths.add(pathname.slice(0, -11));
          paths.add(`${pathname.slice(0, -11)}/`);
        }
      }
    }
  }
  for (const directory of directories ?? await demoDirectories(root)) await visit(path.join(publicRoot, directory));
  return [...paths].sort();
}

export async function technicalPayloadPaths(root = process.cwd()) {
  const publicRoot = path.join(root, "public");
  const paths = [];
  async function visit(directory) {
    for (const entry of await readdir(directory, { withFileTypes: true })) {
      const filename = path.join(directory, entry.name);
      if (entry.isDirectory() && entry.name !== "node_modules") await visit(filename);
      else if (entry.isFile() && entry.name.endsWith(".txt") && entry.name !== "robots.txt") paths.push(`/${path.relative(publicRoot, filename).split(path.sep).map(encodeURIComponent).join("/")}`);
    }
  }
  await visit(publicRoot);
  return paths.sort();
}

export function legacyRedirectRules({ origin, locales, projects, slugs }) {
  const rules = [];
  const add = (from, query, to) => rules.push({ from, query, to, status: 301, force: true });
  // Netlify query matching is exact. Enumerate known slugs; never interpolate an
  // arbitrary user-supplied slug into an indexable destination that may not exist.
  for (const from of ["/", "/index.html", ...locales.map((locale) => `/${locale}`)]) {
    const fallback = locales.includes(from.slice(1)) ? from.slice(1) : "ro";
    for (const project of projects) {
      const slug = slugs[project.id];
      for (const locale of locales) add(from, { lang: locale, proiect: slug }, `${origin}/${locale}/projects/${slug}?`);
      add(from, { proiect: slug }, `${origin}/${fallback}/projects/${slug}?`);
    }
    for (const locale of locales) add(from, { lang: locale }, `${origin}/${locale}?`);
  }
  for (const page of ["contact", "intrebari"]) {
    for (const from of [`/${page}`, `/${page}/index.html`]) {
      for (const locale of locales) {
        if (page === "contact") {
          for (const fields of [["project", "option"], ["project"], ["option"]]) {
            const query = { lang: locale, ...Object.fromEntries(fields.map((key) => [key, `:${key}`])) };
            add(from, query, `${origin}/${locale}/${page}?${fields.map((key) => `${key}=:${key}`).join("&")}`);
          }
        }
        add(from, { lang: locale }, `${origin}/${locale}/${page}?`);
      }
      // Unrecognized parameters are retained so contact prefilling still works.
      add(from, {}, `${origin}/ro/${page}`);
    }
  }
  for (const from of ["/", "/index.html"]) add(from, {}, `${origin}/ro`);
  for (const host of ["http://monodev.md", "http://www.monodev.md", "https://www.monodev.md"]) add(`${host}/*`, {}, `${origin}/:splat`);
  return rules;
}

export function renderRedirects(rules) {
  return "# Generated by scripts/netlify-seo.mjs. Do not edit.\n# Exact legacy queries first; no SPA catch-all. ? clears matched query parameters.\n" + rules.map(({ from, query, to, status, force }) =>
    [from, ...Object.entries(query).map(([key, value]) => `${key}=${value}`), to, `${status}${force ? "!" : ""}`].join(" ")
  ).join("\n") + "\n";
}

export function renderHeaders(htmlPaths, payloadPaths = [], projectPaths = []) {
  const paths = [...new Set(["/admin", "/admin/", "/admin.html", "/admin/index.html", "/admin/*", "/cabinet", "/cabinet/", "/cabinet/index", "/cabinet/index/", "/cabinet/index.html", "/cabinet.html", "/404", "/404/", "/404.html", ...payloadPaths, "/*.rsc", "/.vite/manifest.json"])];
  return "# Generated by scripts/netlify-seo.mjs. Demo HTML, aliases and technical payloads get noindex.\n# Both trailing-slash forms are explicit; image, CSS and JS responses are unaffected.\n" + paths.map((pathname) => `${pathname}\n  X-Robots-Tag: noindex, nofollow\n`).join("\n") + [...new Set([...htmlPaths, ...projectPaths])].map((pathname) => `\n${pathname}\n  X-Robots-Tag: noindex, follow\n`).join("");
}

// Synced demos can bring their original site's index directive back. Change only
// contradictory robots attributes, preserving the rest of each generated document.
export function normalizeDemoRobots(html) {
  return html.replace(/<meta\b[^>]*>/gi, tag => {
    if (!/name\s*=\s*["'](?:robots|googlebot)["']/i.test(tag)) return tag;
    return tag.replace(/(content\s*=\s*)(["'])(.*?)\2/i, (attribute, prefix, quote, value) =>
      /(?:^|[,\s])(?:index|all|nofollow)(?:$|[,\s])/i.test(value)
        ? `${prefix}${quote}noindex, follow${quote}` : attribute);
  });
}

export async function generateNetlifySeo(root = process.cwd()) {
  const { noindexProjectPaths } = loadSiteModule("app/lib/seo-routes.ts", root);
  const projectPaths = noindexProjectPaths();
  const { publicProjects, projectSlugs } = loadSiteModule("app/lib/project-catalog.ts", root);
  const { siteConfig, locales } = loadSiteModule("app/lib/site-config.ts", root);
  const origin = siteConfig.url;
  if (origin !== "https://monodev.md") throw new Error("Unexpected canonical site origin");
  const rules = legacyRedirectRules({ origin, locales: locales ?? siteConfig.locales, projects: publicProjects, slugs: projectSlugs });
  const directories = await demoDirectories(root);
  const htmlPaths = await demoHtmlPaths(root, directories);
  const payloadPaths = await technicalPayloadPaths(root);
  let normalizedDemoFiles = 0;
  for (const pathname of htmlPaths.filter(pathname => pathname.endsWith(".html"))) {
    const filename = path.join(root, "public", decodeURIComponent(pathname.slice(1)));
    const html = await readFile(filename, "utf8");
    const normalized = normalizeDemoRobots(html);
    if (normalized !== html) { await writeFile(filename, normalized, "utf8"); normalizedDemoFiles++; }
  }
  const netlify = await readFile(path.join(root, "netlify.toml"), "utf8");
  if (/\[\[redirects\]\]/.test(netlify)) throw new Error("Keep SEO redirects in generated _redirects, not a second netlify.toml implementation");
  await writeFile(path.join(root, "public/_redirects"), renderRedirects(rules), "utf8");
  await writeFile(path.join(root, "public/_headers"), renderHeaders(htmlPaths, payloadPaths, projectPaths), "utf8");
  return { normalizedDemoFiles, noindexProjectPaths: projectPaths.length, redirectRules: rules.length, demoDirectories: directories.length, noindexHtmlPaths: htmlPaths.length, technicalPayloadPaths: payloadPaths.length };
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) {
  console.log("Netlify SEO:", await generateNetlifySeo());
}
